export const actionType = {
  GET_BOOKS: 'GET_BOOKS',
  GET_BOOK: 'GET_BOOK',
  REMOVE_GET_BOOK: 'REMOVE_GET_BOOK',
  POST_BOOK: 'POST_BOOK',
  UPDATE_BOOK: 'UPDATE_BOOK',
  DELETE_BOOK: 'DELETE_BOOK',
}